name: Publish Documentation

on:
  push:
    branches:
      - main
      - test-actions

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Create cache id from date
        run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV

      - name: Restore cache
        uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      - name: Install MkDocs Material & dependencies
        run: pip install mkdocs-material pillow cairosvg

      - name: Build & deploy GH page
        run: mkdocs gh-deploy --force
